/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Config.clsConexion;
import Entidad.clsEPropietario;
import Negocios.clsNPropietario;
import java.awt.Color;
import java.awt.Insets;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Jefferson
 */
public class frmLogin extends javax.swing.JFrame {
    
    static public String proN;
    static public String proD;
    



    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        
        btnEntrar.setOpaque(true);
        btnRegistro.setOpaque(true);
        tab2.setUI(null);
        tab2.setSelectedIndex(1);
        
        //txtNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
        
        
        //contraseña:
        
        txtContraR.setText("* Contraseña");
        txtContraR.setEchoChar((char)0); // Mostrar el texto tal cual
        
        
        
        txtContraRR.setText("* Repetir Contraseña");
        txtContraRR.setEchoChar((char)0); // Mostrar el texto tal cual
        
        
        
        





    }
    

    
    private void verificarCamposVacios() {
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }

        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }

        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }



        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }

        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }
    }    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnEntrar2 = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JTextField();
        txtUsuario3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtCorreo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        txtDireccion = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        txtContraRR = new javax.swing.JPasswordField();
        txtContraR = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtContra = new javax.swing.JPasswordField();
        btnEntrar1 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblRegistro = new javax.swing.JTextField();
        txtUsuario2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/logoS.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/fondo2.png"))); // NOI18N
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 280, -1));
        bg.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEntrar2.setBackground(new java.awt.Color(41, 148, 204));
        btnEntrar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrar2MouseExited(evt);
            }
        });

        btnRegistro.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistro.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistro.setText("REGISTRARSE");
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEntrar2Layout = new javax.swing.GroupLayout(btnEntrar2);
        btnEntrar2.setLayout(btnEntrar2Layout);
        btnEntrar2Layout.setHorizontalGroup(
            btnEntrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrar2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnEntrar2Layout.setVerticalGroup(
            btnEntrar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrar2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(btnEntrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 120, 40));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setText("REGISTRARSE");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblLogin.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 153, 255));
        lblLogin.setText("Inicia Sesion");
        lblLogin.setBorder(null);
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.setRequestFocusEnabled(false);
        lblLogin.setVerifyInputWhenFocusTarget(false);
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLoginMousePressed(evt);
            }
        });
        lblLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblLoginActionPerformed(evt);
            }
        });
        jPanel3.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 90, 30));

        txtUsuario3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuario3.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario3.setText("¿Ya tienes cuenta?");
        txtUsuario3.setBorder(null);
        txtUsuario3.setOpaque(true);
        txtUsuario3.setRequestFocusEnabled(false);
        txtUsuario3.setVerifyInputWhenFocusTarget(false);
        txtUsuario3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuario3MousePressed(evt);
            }
        });
        txtUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario3ActionPerformed(evt);
            }
        });
        jPanel3.add(txtUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 360, 20));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("* Nombre");
        txtNombre.setBorder(null);
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, 20));

        txtApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("* Apellidos");
        txtApellido.setBorder(null);
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 20));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setText("* Correo Electronico");
        txtCorreo.setBorder(null);
        txtCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 170, 20));

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText("* Telefono");
        txtTelefono.setBorder(null);
        txtTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 180, 30));

        txtDNI.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(204, 204, 204));
        txtDNI.setText("* DNI");
        txtDNI.setBorder(null);
        txtDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDNIMousePressed(evt);
            }
        });
        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        jPanel3.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, 20));

        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        txtDireccion.setText("* Direccion");
        txtDireccion.setBorder(null);
        txtDireccion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDireccionMousePressed(evt);
            }
        });
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, 20));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 20));

        txtContraRR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContraRR.setForeground(new java.awt.Color(204, 204, 204));
        txtContraRR.setText("* Repetir contraseña");
        txtContraRR.setBorder(null);
        txtContraRR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraRRMousePressed(evt);
            }
        });
        txtContraRR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraRRActionPerformed(evt);
            }
        });
        jPanel3.add(txtContraRR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 140, 30));

        txtContraR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContraR.setForeground(new java.awt.Color(204, 204, 204));
        txtContraR.setText("* Contraseña");
        txtContraR.setBorder(null);
        txtContraR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraRMousePressed(evt);
            }
        });
        txtContraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraRActionPerformed(evt);
            }
        });
        jPanel3.add(txtContraR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        tab2.addTab("tab2", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel2.setText("INICIAR SESIÓN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblUsuario.setText("CONTRASEÑA");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 20));

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su nombre usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 190, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 270, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 270, 20));

        txtContra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContra.setForeground(new java.awt.Color(204, 204, 204));
        txtContra.setText("**************");
        txtContra.setBorder(null);
        txtContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtContraMousePressed(evt);
            }
        });
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        jPanel2.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 30));

        btnEntrar1.setBackground(new java.awt.Color(41, 148, 204));
        btnEntrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrar1MouseExited(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(102, 153, 255));
        btnEntrar.setFont(new java.awt.Font("Roboto Condensed", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEntrar.setText("ENTRAR");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEntrar1Layout = new javax.swing.GroupLayout(btnEntrar1);
        btnEntrar1.setLayout(btnEntrar1Layout);
        btnEntrar1Layout.setHorizontalGroup(
            btnEntrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnEntrar1Layout.setVerticalGroup(
            btnEntrar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEntrar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(btnEntrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 120, 40));

        lblUsuario1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lblUsuario1.setText("USUARIO");
        jPanel2.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 20));

        lblRegistro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblRegistro.setForeground(new java.awt.Color(0, 153, 255));
        lblRegistro.setText("Registrate");
        lblRegistro.setBorder(null);
        lblRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistro.setRequestFocusEnabled(false);
        lblRegistro.setVerifyInputWhenFocusTarget(false);
        lblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegistroMousePressed(evt);
            }
        });
        lblRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRegistroActionPerformed(evt);
            }
        });
        jPanel2.add(lblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 70, 30));

        txtUsuario2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuario2.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario2.setText("¿No tienes cuenta?");
        txtUsuario2.setBorder(null);
        txtUsuario2.setOpaque(true);
        txtUsuario2.setRequestFocusEnabled(false);
        txtUsuario2.setVerifyInputWhenFocusTarget(false);
        txtUsuario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuario2MousePressed(evt);
            }
        });
        txtUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 120, 30));

        tab2.addTab("tab1", jPanel2);

        bg.add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 400, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed
        // TODO add your handling code here:
        
        if(txtUsuario.getText().equals("Ingrese su nombre usuario"))            
        {
            txtUsuario.setText("");
            txtUsuario.setForeground(Color.black);            
                         
        }
        
        if(String.valueOf(txtContra.getPassword()).isEmpty())

        {
            
            txtContra.setText("**************");
            txtContra.setForeground(new Color(204,204,204));
        
        }            
       
        
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void txtContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraMousePressed
        // TODO add your handling code here:
        
        if(String.valueOf(txtContra.getPassword()).equals("**************"))
        
        {
            
            txtContra.setText("");
            txtContra.setForeground(Color.black);
        
        }

        if(txtUsuario.getText().isEmpty())
        
        
        {
        
            txtUsuario.setText("Ingrese su nombre usuario");
            txtUsuario.setForeground(new Color(204,204,204));
            
        }


        
        
    }//GEN-LAST:event_txtContraMousePressed

    private void btnEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseEntered
        // TODO add your handling code here:
        
        btnEntrar.setBackground(new Color(132,173,255));
        
    }//GEN-LAST:event_btnEntrarMouseEntered

    private void btnEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseExited
        // TODO add your handling code here:
        btnEntrar.setBackground(new Color(102,153,255));
        
    }//GEN-LAST:event_btnEntrarMouseExited

    private void btnEntrar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseEntered
        
        
    }//GEN-LAST:event_btnEntrar1MouseEntered

    private void btnEntrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar1MouseExited
    }//GEN-LAST:event_btnEntrar1MouseExited

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
        
        
        String usuario = txtUsuario.getText().trim();
        String contra = new String(txtContra.getPassword()).trim();
        
        
            // Validar campos vacíos
        if (usuario.isEmpty() || contra.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese usuario y contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
     
        }


    try {
        // Conectar a la base de datos
        clsConexion conexion = new clsConexion();
        Connection con = conexion.getConnection();

            if (con == null) {
                JOptionPane.showMessageDialog(this, "No se pudo establecer conexión con la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Preparar la consulta
            String sql = "SELECT * FROM tbPropietario WHERE dni = ? AND contra = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, usuario);
            ps.setString(2, contra);

            ResultSet rs = ps.executeQuery();


            if (rs.next()) {
                // Usuario encontrado
                JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso.");
                
                clsNPropietario objN = new clsNPropietario();
                String nombre = objN.MtdObtenerNombrePorDni(usuario); // donde usuario = DNI
                
                JOptionPane.showMessageDialog(this, "Bienvenido, " + nombre);
                
                proD = usuario;
                
                proN = nombre;
                
                new frmPropietario().setVisible(true);
                

        
                
                
                /*
                
                



                // Obtener cargo desde la clase de negocios
                clsNPropietario objNC = new clsNPropietario();
                int idCargo = objNC.MtdObtenerIdCargoPorDni(usuario);

                empN = objNC.MtdObtenerNombrePorDni(usuario);
                empD = txtUsuario.getText();


                // Redirigir según el cargo
                            String nombreEmp = rs.getString("nombre") + " " + rs.getString("apellido");
                
                
                */
                
                


                this.dispose(); // Cerrar login

            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            rs.close();
            ps.close();
            con.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error en base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); // Para ver el error en consola
        }
        
        
    
        
        
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void lblRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistroMousePressed

    private void lblRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRegistroActionPerformed

    private void txtUsuario2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuario2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario2MousePressed

    private void txtUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario2ActionPerformed

    private void lblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistroMouseClicked
        // TODO add your handling code here:
        
        tab2.setSelectedIndex(0);
        
        
        
        
        
    }//GEN-LAST:event_lblRegistroMouseClicked

    
    private void limpiarCamposRegistro() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtDNI.setText("");
        txtContra.setText("");
        txtContraR.setText("");
        txtContraRR.setText("");
    }    
    
    
    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        // TODO add your handling code here:
        
        // Obtener datos de los campos
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String direccion = txtDireccion.getText().trim();
        String correo = txtCorreo.getText().trim();
        String telefono = txtTelefono.getText().trim();
        String dni = txtDNI.getText().trim();
        String contra = String.valueOf(txtContraR.getPassword()).trim();
        String contraRep = String.valueOf(txtContraRR.getPassword()).trim();

        // Validar campos vacíos
        if (nombre.isEmpty() || apellido.isEmpty() || direccion.isEmpty() || correo.isEmpty() || 
            telefono.isEmpty() || dni.isEmpty() || contra.isEmpty() || contraRep.isEmpty()) {

            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
            return;
        }

        // Validar que las contraseñas coincidan
        if (!contra.equals(contraRep)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            return;
        }

        // Instanciar entidad y negocio
        clsEPropietario objEC = new clsEPropietario();
        clsNPropietario objNC = new clsNPropietario();

        // Setear valores
        objEC.setNombre(nombre);
        objEC.setApellido(apellido);
        objEC.setDireccion(direccion);
        objEC.setCorreo(correo);
        objEC.setTelefono(telefono);
        objEC.setDni(dni);
        objEC.setContra(contra); // Guardar la contraseña validada

        // Registrar en BD
        if (objNC.MtdRegistrarPropietario(objEC)) {
            JOptionPane.showMessageDialog(null, "Usuario Registrado Correctamente!");
            
            limpiarCamposRegistro();
            
            verificarCamposVacios();
            
        } else {
            JOptionPane.showMessageDialog(null, "ERROR al registrar usuario.");
        }


        
        
    }//GEN-LAST:event_btnRegistroMouseClicked

    private void btnRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseEntered
        // TODO add your handling code here:
        
        btnRegistro.setBackground(new Color(132,173,255));
        
        
    }//GEN-LAST:event_btnRegistroMouseEntered

    private void btnRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseExited
        // TODO add your handling code here:
        
        btnEntrar.setBackground(new Color(102,153,255));
        
    }//GEN-LAST:event_btnRegistroMouseExited

    private void btnEntrar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar2MouseEntered

    private void btnEntrar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrar2MouseExited

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        tab2.setSelectedIndex(1);
        
        
        
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoginMousePressed

    private void lblLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLoginActionPerformed

    private void txtUsuario3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuario3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario3MousePressed

    private void txtUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario3ActionPerformed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
        
        if(txtNombre.getText().equals("* Nombre")){
        txtNombre.setText("");
        txtNombre.setForeground(Color.BLACK);
        
        
        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }

        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }

        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }



        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }

        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }        
        
        }
        
        
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        // TODO add your handling code here:
        
        if(txtApellido.getText().equals("* Apellidos")){
        txtApellido.setText("");
        txtApellido.setForeground(Color.BLACK);
        
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }



        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }

        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }



        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }

        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }        
        
        
        }        
        
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
        if(txtCorreo.getText().equals("* Correo Electronico")){
        txtCorreo.setText("");
        txtCorreo.setForeground(Color.BLACK);
        
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }

        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }


        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }

        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }



        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }

        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }
        }         
        
        
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        if(txtTelefono.getText().equals("* Telefono")){
        txtTelefono.setText("");
        txtTelefono.setForeground(Color.BLACK);
        
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }

        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }



        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }



        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }

        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }
        
        
        }           
        
        
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
     
        
        
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDNIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDNIMousePressed
        // TODO add your handling code here:
        
        if(txtDNI.getText().equals("* DNI")){
        txtDNI.setText("");
        txtDNI.setForeground(Color.BLACK);
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }

        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }





        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }

        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }
        }
        

        
    }//GEN-LAST:event_txtDNIMousePressed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void txtDireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDireccionMousePressed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(txtDireccion.getText().equals("* Direccion")){
        txtDireccion.setText("");
        txtDireccion.setForeground(Color.BLACK);
        
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }



        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }

        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }



        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }

        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }
        
        }           
        
    }//GEN-LAST:event_txtDireccionMousePressed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtContraRRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraRRMousePressed
        // TODO add your handling code here:
        
        if (String.valueOf(txtContraRR.getPassword()).equals("* Repetir Contraseña")) {
        txtContraRR.setText("");
        txtContraRR.setEchoChar('•'); // Mostrar asteriscos
        txtContraRR.setForeground(Color.BLACK);
        
        if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }

        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }

        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }



        if (String.valueOf(txtContraR.getPassword()).trim().isEmpty()) {
            txtContraR.setText("* Contraseña");
            txtContraR.setForeground(new Color(204,204,204));
        }


        
        }
        
    }//GEN-LAST:event_txtContraRRMousePressed

    private void txtContraRRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraRRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraRRActionPerformed

    private void txtContraRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraRMousePressed
        // TODO add your handling code here:
        
        if (String.valueOf(txtContraR.getPassword()).equals("* Contraseña")) {
        txtContraR.setText("");
        txtContraR.setEchoChar('•'); // Mostrar asteriscos
        txtContraR.setForeground(Color.BLACK);
        
if (txtNombre.getText().trim().isEmpty()) {
            txtNombre.setText("* Nombre");
            txtNombre.setForeground(new Color(204,204,204));
        }

        if (txtApellido.getText().trim().isEmpty()) {
            txtApellido.setText("* Apellidos");
            txtApellido.setForeground(new Color(204,204,204));
        }

        if (txtDireccion.getText().trim().isEmpty()) {
            txtDireccion.setText("* Direccion");
            txtDireccion.setForeground(new Color(204,204,204));
        }

        if (txtCorreo.getText().trim().isEmpty()) {
            txtCorreo.setText("* Correo Electronico");
            txtCorreo.setForeground(new Color(204,204,204));
        }

        if (txtTelefono.getText().trim().isEmpty()) {
            txtTelefono.setText("* Telefono");
            txtTelefono.setForeground(new Color(204,204,204));
        }

        if (txtDNI.getText().trim().isEmpty()) {
            txtDNI.setText("* DNI");
            txtDNI.setForeground(new Color(204,204,204));
        }





        if (String.valueOf(txtContraRR.getPassword()).trim().isEmpty()) {
            txtContraRR.setText("* Repetir Contraseña");
            txtContraRR.setForeground(new Color(204,204,204));
        }        
        
        }
        
        
    }//GEN-LAST:event_txtContraRMousePressed

    private void txtContraRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnEntrar;
    private javax.swing.JPanel btnEntrar1;
    private javax.swing.JPanel btnEntrar2;
    private javax.swing.JLabel btnRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lblLogin;
    private javax.swing.JTextField lblRegistro;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JTabbedPane tab2;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JPasswordField txtContraR;
    private javax.swing.JPasswordField txtContraRR;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuario2;
    private javax.swing.JTextField txtUsuario3;
    // End of variables declaration//GEN-END:variables
}
